version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      bookify-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=Bookify;User Id=sa;Password=gH9#kL$4p@3qW!;TrustServerCertificate=true;

  bookify-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Bookify.Db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'gH9#kL$4p@3qW!'
      SQL_AGENT_ENABLED: 'true'
    volumes:
      - bookify-db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P gH9#kL$4p@3qW! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  bookify-db-data:
