version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
        - bookify-db

  bookify-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bookify-db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'gH9#kL$4p@3qW!'
      SQL_AGENT_ENABLED: 'true'
    volumes:
      - bookify-db-data:/var/opt/mssql
    ports:
      - "1433:1433"

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

volumes:
  bookify-db-data:
